const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
const menu=['Dashboard','Companies','Map','IoT','Energy','Water','Gas','Carbon','Waste','Environment','Social','Governance','ESG Rating','Reports','Analytics','AI Assistant','Knowledge Center','ESG Academy','Eco Projects','Climate Projects','Sensors','Documents','Audit','Settings','Admin'];
const features=['О платформе','Возможности','ESG Dashboard','IoT','AI','SDG','ESG Rating','Карта Казахстана','Карта Алматы','Мониторинг предприятий','Мониторинг воздуха','Мониторинг отходов','Экологические проекты','Новости ESG','Статьи','Партнеры','Отзывы','FAQ','Контакты'];
const counters=['Компаний','Пользователей','Датчиков','Деревьев','Проектов','ESG аудитов','Школ','Университетов','т переработанных отходов','т CO₂ снижено'];
const companies=['KazEnergy Grid','Almaty Smart City','Green School №42','EcoPack Industry','Astana University','MedCenter CarbonCare','Karaganda Steel','Qazaq Solar'];
const sensors=['ESP32','ESP8266','Arduino','Raspberry Pi','LoRaWAN','NB-IoT','MQTT','REST API','Modbus','BACnet','OPC-UA','Schneider','ABB','Siemens','Mercury','Kamstrup'];
const metrics=['Энергия','Вода','Газ','Температура','Влажность','Освещенность','Шум','Вибрация','CO₂','PM2.5','PM10','VOC','NH₃','NO₂','SO₂','O₃','Уровень воды','Расход','Давление'];
const initiatives=['Посадка деревьев','Школьный экологический клуб','Поддержка университетов','STEM лаборатория','Раздельный сбор отходов','LED освещение','Солнечные панели','Автоматизация отопления','Водосбережение','Экологическое обучение','Компенсация выбросов','Восстановление парков','Создание питомников','Электромобили','Зеленые закупки','Электронный документооборот','ESG стратегия','ESG отчет'];
const topics=['Что такое ESG','Что такое SDG','Как начать ESG','Первые шаги','ESG стратегия','GRI','ISSB','ESRS','ISO 14001','ISO 50001','ISO 45001','ISO 26000','Scope 1','Scope 2','Scope 3','Углеродный след','Энергоэффективность','Водосбережение','Управление отходами','Биоразнообразие','Декарбонизация','Круговая экономика','Климатические риски','Зеленые закупки','Социальная ответственность','Корпоративное управление','ESG KPI','ESG рейтинг','Лучшие мировые практики','Типичные ошибки','Практические рекомендации'];
const projects=['Посадка деревьев','Озеленение','Очистка рек','Переработка','Раздельный сбор','Энергоэффективность','Солнечная энергетика','Ветроэнергетика','Поддержка школ','Поддержка университетов','Поддержка детских садов','Поддержка питомников','Климатические проекты'];
function card(title,body,cls='feature-card'){return `<article class="${cls}"><h3>${title}</h3><p>${body}</p></article>`}
function boot(){setTimeout(()=>$('#loader').classList.add('hidden'),700);$('#mainMenu').innerHTML=menu.map(m=>`<a href="#${m.toLowerCase().replaceAll(' ','').replace('esgrating','rating').replace('knowledgecenter','knowledge').replace('esgacademy','academy').replace('ecoprojects','projects')}">${m}</a>`).join('');
$('#featuresGrid').innerHTML=features.map((f,i)=>card(f,`Модуль с glassmorphism UI, SVG и enterprise workflow #${i+1}.`)).join('');
$('#counterGrid').innerHTML=counters.map((c,i)=>`<div class="kpi-card"><span>${c}</span><strong data-count="${(i+2)*1370}">0</strong><progress value="${50+i*4}" max="100"></progress></div>`).join('');
$('#kpiGrid').innerHTML=Array.from({length:50},(_,i)=>`<div class="kpi-card"><span>KPI ${i+1}</span><strong>${(80+Math.random()*900).toFixed(i%3?0:1)}</strong><small>${['Energy','Water','Carbon','Waste','Social'][i%5]} analytics</small></div>`).join('');
$('#chartsGrid').innerHTML=Array.from({length:20},(_,i)=>`<div class="chart-card"><h3>Аналитическая панель ${i+1}</h3><canvas id="chart${i}"></canvas></div>`).join('');
$('#companyRows').innerHTML=companies.map((c,i)=>`<tr><td>${c}</td><td>${['Алматы','Астана','Караганда'][i%3]}</td><td>${['AAA','AA','A','BBB'][i%4]}</td><td>${1200+i*310} т</td><td>${(2.4+i*.7).toFixed(1)} GWh</td><td>${8+i}</td><td><span class="status">Online</span></td></tr>`).join('');
$('#deviceGrid').innerHTML=sensors.map((s,i)=>`<div class="device-card"><h3>${s}</h3><p>${metrics[i%metrics.length]} · RSSI ${-45-i} · Battery ${95-i}%</p><progress value="${95-i}" max="100"></progress><small>${i%5?'Online':'Offline'} · Последнее обновление ${i+1} мин назад</small></div>`).join('');
$('#ratingGrid').innerHTML=['Компании','Города','Регионы','Отрасли','Школы','Университеты','Больницы'].map((r,i)=>`<div class="rating-card"><h3>${r}</h3><strong>${['AAA','AA','A','BBB','BB','B','CCC'][i]}</strong><p>Национальный индекс прозрачности и устойчивости.</p></div>`).join('');
$('#initiativeGrid').innerHTML=initiatives.map((x,i)=>`<div class="initiative-card"><h3>${x}</h3><p>Стоимость: ${(i+1)*450}k ₸ · срок ${2+i%8} мес · CO₂ -${12+i*4} т · ESG +${1+i%7}</p><progress value="${40+i*3}" max="100"></progress><small>E +${i%5+1} · S +${i%4+1} · G +${i%3+1}</small></div>`).join('');
$('#academyGrid').innerHTML=['Курсы','Видео','PDF','Презентации','Домашние задания','Тесты','Экзамены','Сертификаты','Прогресс'].map((a,i)=>`<div class="academy-card"><h3>${a}</h3><p>Личный кабинет и трек компетенций.</p><progress value="${55+i*4}" max="100"></progress></div>`).join('');
$('#articleGrid').innerHTML=Array.from({length:100},(_,i)=>card(topics[i%topics.length],`Инфографика, чек-лист, пошаговая инструкция, FAQ и связанные статьи.`, 'article-card')).join('');
$('#projectGrid').innerHTML=projects.map((p,i)=>`<div class="project-card"><h3>${p}</h3><p>SDG ${i%17+1} · бюджет ${(i+1)*2} млн ₸ · участники ${80+i*25} · CO₂ -${50+i*18} т</p></div>`).join('');
makeCharts();makeMaps();makeForms();bindUI();animateCounters();}
function makeCharts(){const colors=['#38e8a4','#55a7ff','#ffd166','#ff6384'];new Chart($('#heroChart'),{type:'doughnut',data:{labels:['E','S','G'],datasets:[{data:[87,78,82],backgroundColor:colors}]},options:{plugins:{legend:{labels:{color:'#fff'}}}}});$$('canvas[id^=chart]').forEach((c,i)=>new Chart(c,{type:i%3?'line':'bar',data:{labels:['Янв','Фев','Мар','Апр','Май','Июн'],datasets:[{label:'Факт',data:Array.from({length:6},()=>Math.random()*100),borderColor:colors[i%4],backgroundColor:colors[i%4]+'88'}]},options:{plugins:{legend:{labels:{color:'#fff'}}},scales:{x:{ticks:{color:'#92a9c5'}},y:{ticks:{color:'#92a9c5'}}}}}));new Chart($('#iotTrend'),{type:'line',data:{labels:metrics.slice(0,8),datasets:[{label:'Trend',data:[12,18,16,22,30,28,36,44],borderColor:'#38e8a4'}]}});new Chart($('#deviceStatus'),{type:'pie',data:{labels:['Online','Offline'],datasets:[{data:[92,8],backgroundColor:['#38e8a4','#ff6384']} ]}})}
function makeMaps(){const popup=p=>`<b>${p}</b><br>ESG карточка, датчики, документы, ответственные лица.`;let kz=L.map('kazakhstanMap').setView([48.0,67.0],5), al=L.map('almatyMap').setView([43.238,76.889],11);[kz,al].forEach(m=>L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OSM'}).addTo(m));[[43.24,76.9,'Almaty Smart City'],[51.16,71.47,'Astana University'],[49.8,73.1,'Karaganda Steel']].forEach(x=>L.marker([x[0],x[1]]).addTo(kz).bindPopup(popup(x[2])));[[43.25,76.95,'PM2.5 station'],[43.22,76.85,'Экопункт'],[43.28,76.91,'Парк и деревья']].forEach(x=>L.circleMarker([x[0],x[1]],{radius:10,color:'#38e8a4'}).addTo(al).bindPopup(popup(x[2])))}
function makeForms(){let fields=['Тип организации','Отрасль','Размер компании','Количество сотрудников','Регион','Город','Адрес','GPS','Площадь','Количество зданий','Количество филиалов','Тип отопления','Источник воды','Источник электроэнергии','Количество счетчиков','Количество датчиков','Солнечные панели','Очистные сооружения','ESG стратегия','ESG отчет'];$('#onboardingForm').innerHTML=fields.map(f=>`<label>${f}<input name="${f}" placeholder="${f}"></label>`).join('');$('#companyProfile').innerHTML=`<h2>KazEnergy Grid</h2><p>Логотип, фото, описание, ESG история, Environment/Social/Governance, энергия, вода, газ, CO₂, PM2.5, PM10, VOC, отходы, сотрудники, филиалы, здания, деревья, климатические проекты, аудиты, показания, документы, контакты.</p><div class="charts-grid"><div class="chart-card"><canvas id="profileChart"></canvas></div></div>`}
function bindUI(){$$('[data-modal]').forEach(b=>b.onclick=()=>$('#'+b.dataset.modal).classList.add('open'));$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('open'));$('#refreshBtn').onclick=()=>toast('Аномалии, прогнозы и KPI обновлены');$('#notifyBtn').onclick=()=>toast('AI: обнаружен рост CO₂ и энергопотребления');$('#saveCompany').onclick=()=>{localStorage.setItem('esgCompany',JSON.stringify(Object.fromEntries(new FormData($('#onboardingForm')))));toast('Компания сохранена в LocalStorage')}}
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2400)}function animateCounters(){$$('[data-count]').forEach(e=>{let n=+e.dataset.count;e.textContent=n.toLocaleString('ru-RU')})}
document.addEventListener('DOMContentLoaded',boot);
