const nav=[['iot.html','IoT Dashboard'],['connect-device.html','Подключение датчиков'],['map.html','Карта предприятий'],['pollution-map.html','Карта загрязнений'],['rating.html','ESG Rating'],['companies.html','Каталог компаний'],['company.html','Страница компании'],['join.html','ESG Alliance'],['audit.html','ESG аудит'],['company-connect.html','Подключить компанию'],['waste-monitoring.html','Мониторинг отходов'],['eco-partners.html','Экопартнеры'],['landfills.html','Мониторинг свалок'],['consumption.html','Потребление'],['deviations.html','Отклонения'],['recommendations.html','AI Recommendations']];
const sensors=['Электроэнергия','Вода','Газ','CO₂','PM2.5','PM10','VOC','Температура','Влажность','Освещенность','Шум','Вибрация','Уровень воды','Скорость ветра','Осадки'];
const companies=[['EcoSteel','Металлургия','Алматы',87,1200,4],['Green School','Образование','Астана',93,180,2],['MedClean','Здравоохранение','Шымкент',82,650,3],['AgroNursery','Питомники','Костанай',91,75,6],['Solar Office','IT','Алматы',89,320,1],['Aqua Plant','Производство','Атырау',78,980,5]];
function seed(){if(!localStorage.esgData)localStorage.esgData=JSON.stringify({updated:new Date().toISOString(),applications:[],devices:[],audits:[],objects:companies.map((c,i)=>({name:c[0],type:['Завод','Школа','Больница','Питомник','Офис','Теплица'][i],city:c[2],score:c[3],employees:c[4],lat:43.23+i*.42,lng:76.88-i*.55,co2:900+i*120,energy:1200-i*80,water:420+i*35,trees:1000+i*230,audit:'2026-06-'+String(10+i).padStart(2,'0')}))})}function db(){return JSON.parse(localStorage.esgData)}function save(d){localStorage.esgData=JSON.stringify(d)}
function layout(title,subtitle){seed();document.body.innerHTML=`<div class="app"><aside class="sidebar"><a class="brand" href="iot.html"><div class="logo"></div><div><h1>ESG Azure</h1><span>IoT & Sustainability Cloud</span></div></a><nav class="nav">${nav.map(([h,t])=>`<a href="${h}" class="${location.pathname.endsWith(h)?'active':''}">${t}</a>`).join('')}</nav></aside><main class="main"><div class="topbar"><div class="title"><h2>${title}</h2><p>${subtitle}</p></div><div class="actions"><a class="btn primary" href="join.html">Вступить в ESG Alliance</a><a class="btn" href="audit.html">Пройти ESG аудит</a></div></div><div id="content"></div></main></div>`;return document.getElementById('content')}
function chart(id,type,labels,data,label='Показатель'){new Chart(document.getElementById(id),{type,data:{labels,datasets:[{label,data,borderColor:'#59b6ff',backgroundColor:'rgba(89,182,255,.25)',fill:type==='line',tension:.35}]},options:{responsive:true,plugins:{legend:{labels:{color:'#dbeafe'}}},scales:{x:{ticks:{color:'#91a8c5'},grid:{color:'#1d3855'}},y:{ticks:{color:'#91a8c5'},grid:{color:'#1d3855'}}}}});}
function initEnterpriseMap(id,selectable=true){const d=db();const m=L.map(id).setView([43.6,74.8],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(m);d.objects.forEach(o=>L.marker([o.lat,o.lng]).addTo(m).bindPopup(`<b>${o.name}</b><br>${o.type}<br>ESG: ${o.score}<br>Выбросы: ${o.co2} т<br>Энергия: ${o.energy} МВт⋅ч<br>Вода: ${o.water} м³<br>Сотрудники: ${o.employees}<br>Деревья: ${o.trees}<br>Аудит: ${o.audit}`));return m}
function statCards(items){return `<div class="grid cols-4">${items.map(i=>`<div class="card metric"><div><span>${i[0]}</span><br><b>${i[1]}</b></div><span class="pill ${i[2]||''}">${i[3]||'live'}</span></div>`).join('')}</div>`}
function bindForm(id,key,msg){document.getElementById(id).onsubmit=e=>{e.preventDefault();const d=db();d[key].push(Object.fromEntries(new FormData(e.target)));save(d);alert(msg);e.target.reset()}}
function wizard(root,steps,done){let i=0;const render=()=>{root.innerHTML=`<div class="steps">${steps.map((s,n)=>`<div class="step ${n===i?'active':''}">${n+1}. ${s.t}</div>`).join('')}</div><div class="card">${steps[i].h}<br><br><button class="btn" id="prev">Назад</button> <button class="btn primary" id="next">${i===steps.length-1?'Завершить':'Далее'}</button></div>`;prev.onclick=()=>{i=Math.max(0,i-1);render()};next.onclick=()=>{if(i===steps.length-1){done&&done();return}i++;render()}};render()}
function pollutionMap(id){const m=L.map(id).setView([43.24,76.92],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png').addTo(m);for(let i=0;i<36;i++){const aqi=Math.floor(30+Math.random()*140),color=aqi<60?'green':aqi<110?'yellow':'red';L.circle([43.18+Math.random()*.15,76.82+Math.random()*.18],{radius:500+aqi*8,color,fillColor:color,fillOpacity:.35}).addTo(m).bindPopup(`AQI ${aqi}<br>PM2.5 ${Math.round(aqi/2)}<br>PM10 ${aqi}<br>CO₂ ${420+aqi}`)}}
