import { api, docs, labs, modules, roles, sdgs } from '@/lib/platform-data';
import { BookOpen, Bot, CalendarDays, FileText, GraduationCap, LayoutDashboard, Leaf, Lock, Search, ShieldCheck, Users } from 'lucide-react';

const stats = [['12 480','учащихся'],['386','сотрудников'],['217','проектов'],['9','лабораторий'],['1 240','документов'],['17','SDG направлений']];
const features = [
  ['Модульная SaaS-архитектура','Мультитенантность для школ, колледжей, университетов и SDG Centre Казахстана.'],
  ['Единый рабочий контур','Официальный сайт, LMS, DMS, Knowledge Centre, LIMS, HRM, PMS, ESG и BI в одной системе.'],
  ['Безопасность enterprise-класса','JWT, Google/Microsoft OAuth, 2FA, RBAC, Audit Log, согласование документов и резервные копии.'],
  ['AI-first операционная модель','Внутренний помощник отвечает по нормативной базе, проектам, KPI, ESG и Carbon AI.'],
];
function H({children}:{children:React.ReactNode}){return <h2 className="text-3xl font-black tracking-tight sm:text-4xl">{children}</h2>}
export default function Home(){return <main>
<nav className="sticky top-0 z-50 border-b border-slate-200 bg-white/85 backdrop-blur dark:border-slate-800 dark:bg-slate-950/85"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3"><div className="flex items-center gap-3 font-black"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-emerald-500 text-white">SDG</span><span>Centre OS + Carbon AI</span></div><div className="hidden gap-6 text-sm font-semibold lg:flex"><a href="#platform">Платформа</a><a href="#knowledge">База знаний</a><a href="#lms">LMS</a><a href="#carbon">Carbon AI</a><a href="#admin">Администрирование</a></div><button className="rounded-full bg-slate-950 px-5 py-2 text-sm font-bold text-white dark:bg-white dark:text-slate-950">Личный кабинет</button></div></nav>
<section className="relative overflow-hidden bg-[radial-gradient(circle_at_top_left,#bbf7d0,transparent_36%),linear-gradient(135deg,#ecfeff,#f8fafc_50%,#ecfdf5)] dark:bg-[radial-gradient(circle_at_top_left,#065f46,transparent_36%),linear-gradient(135deg,#020617,#0f172a_55%,#052e2b)]"><div className="section grid gap-10 lg:grid-cols-[1.1fr_.9fr]"><div className="py-10"><span className="pill">Национальная SaaS-платформа устойчивого развития</span><h1 className="mt-6 text-5xl font-black leading-tight tracking-tight sm:text-7xl">Единая цифровая операционная система SDG Centre</h1><p className="mt-6 max-w-2xl text-lg text-slate-600 dark:text-slate-300">Корпоративная экосистема уровня Microsoft Learn, Notion, GitBook, Moodle, Teams и Jira для управления обучением, документами, лабораториями, проектами, ESG и Carbon AI.</p><div className="mt-8 flex flex-wrap gap-3">{['Подать заявку','Стать партнером','Записаться','Личный кабинет'].map(x=><button className="rounded-full bg-emerald-500 px-6 py-3 font-bold text-white shadow-glow" key={x}>{x}</button>)}</div></div><div className="glass my-8 rounded-[2rem] p-5"><div className="grid grid-cols-2 gap-3">{stats.map(([n,l])=><div className="rounded-3xl bg-white/70 p-5 dark:bg-slate-800/70" key={l}><div className="text-3xl font-black text-emerald-600">{n}</div><div className="text-sm text-slate-500">{l}</div></div>)}</div><div className="mt-4 rounded-3xl bg-slate-950 p-5 text-white"><div className="flex items-center gap-2"><LayoutDashboard/> Live Dashboard</div><div className="mt-4 h-32 rounded-2xl bg-gradient-to-r from-emerald-400 via-cyan-400 to-blue-500"/></div></div></div></section>
<section id="platform" className="section"><H>Миссия, видение и архитектура платформы</H><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{features.map(([t,d])=><div className="card" key={t}><ShieldCheck className="text-emerald-500"/><h3 className="mt-4 text-xl font-bold">{t}</h3><p className="mt-2 text-slate-600 dark:text-slate-300">{d}</p></div>)}</div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{modules.map(m=><span className="rounded-2xl border border-slate-200 bg-white p-4 text-center font-bold dark:border-slate-800 dark:bg-slate-900" key={m}>{m}</span>)}</div></section>
<section className="section"><H>Роли, кабинеты и права доступа</H><p className="mt-3 text-slate-600 dark:text-slate-300">Каждая роль получает персональный кабинет: профиль, расписание, уведомления, проекты, задачи, KPI, достижения, сертификаты, документы, сообщения и отчеты.</p><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{roles.map(r=><div className="card" key={r}><Users className="text-emerald-500"/><b>{r}</b><p className="mt-2 text-sm text-slate-500">RBAC-права, рабочие виджеты, уведомления и audit trail.</p></div>)}</div></section>
<section id="knowledge" className="section"><H>Knowledge Centre и нормативная база SDG Centre</H><div className="mt-8 grid gap-6 lg:grid-cols-[280px_1fr]"><aside className="card sticky top-20 h-fit"><b>Дерево навигации</b>{docs.map(d=><a className="mt-3 block text-sm text-slate-600 dark:text-slate-300" href={`#${d.group}`} key={d.group}>{d.group}</a>)}</aside><div className="space-y-5">{docs.map(d=><article id={d.group} className="card" key={d.group}><div className="flex items-center justify-between"><h3 className="text-2xl font-black">{d.group}</h3><FileText className="text-emerald-500"/></div><p className="mt-2 text-sm text-slate-500">HTML-страницы документов с оглавлением, хлебными крошками, поиском, версиями, экспортом PDF/Word, печатью, закладками, комментариями, связанными документами и кнопками Назад/Далее.</p><div className="mt-4 flex flex-wrap gap-2">{d.items.map(i=><span className="pill" key={i}>{i}</span>)}</div></article>)}</div></div></section>
<section id="lms" className="section"><H>LMS, библиотека, лаборатории и проекты</H><div className="mt-8 grid gap-5 lg:grid-cols-3"><div className="card"><GraduationCap className="text-emerald-500"/><h3 className="text-xl font-bold">Обучение</h3><p>Курсы, видео, презентации, тесты, домашние задания, сертификаты, рейтинг, журнал и прогресс.</p></div><div className="card"><BookOpen className="text-emerald-500"/><h3 className="text-xl font-bold">Электронная библиотека</h3><p>Поиск, фильтры, категории, избранное, версии, связанные материалы и быстрый переход.</p></div><div className="card"><CalendarDays className="text-emerald-500"/><h3 className="text-xl font-bold">Календарь мероприятий</h3><p>События, бронирование лабораторий, дедлайны проектов, интеграция с email и календарями.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{labs.map(l=><div className="rounded-3xl bg-emerald-50 p-5 font-bold text-emerald-900 dark:bg-emerald-950 dark:text-emerald-100" key={l}>{l}<p className="mt-2 text-sm font-normal">Оборудование, инвентаризация, инструкции, проекты, исследования, бронирование, фото, видео и документы.</p></div>)}</div></section>
<section id="carbon" className="section"><H>ESG + Carbon AI</H><div className="mt-8 grid gap-5 lg:grid-cols-2"><div className="card"><Leaf className="text-emerald-500"/><h3 className="text-2xl font-black">ESG-платформа</h3><p>ESG-рейтинг, методики, индикаторы, отчеты, обучение, аналитические панели и Carbon Accounting.</p></div><div className="card"><Bot className="text-emerald-500"/><h3 className="text-2xl font-black">Carbon AI</h3><p>Калькулятор CO₂, реестр деревьев, экологический мониторинг, климатические проекты, AI-рекомендации, карты и аналитика.</p></div></div><div className="mt-6 grid grid-cols-2 gap-2 md:grid-cols-4 lg:grid-cols-6">{sdgs.map((s,i)=><div className="rounded-2xl bg-slate-900 p-4 text-sm font-bold text-white" key={s}>SDG {i+1}<br/><span className="text-emerald-300">{s}</span></div>)}</div></section>
<section id="admin" className="section"><H>Backend, API и администрирование</H><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-5">{api.map(a=><div className="card" key={a}><Lock className="text-emerald-500"/><b>{a}</b></div>)}</div><div className="mt-8 rounded-[2rem] bg-slate-950 p-8 text-white"><Search/><h3 className="mt-3 text-2xl font-black">Глобальный поиск</h3><p className="mt-2 text-slate-300">Meilisearch/Elasticsearch индексирует документы, проекты, сотрудников, оборудование, лаборатории, новости, курсы, статьи и мероприятия.</p></div></section>
<footer className="border-t border-slate-200 py-10 text-center text-sm text-slate-500 dark:border-slate-800">© 2026 SDG Centre OS — готовая коммерческая платформа для тиражирования.</footer>
</main>}
